name: Actualiza Stock
on:
  workflow_dispatch:
  schedule:
    - cron: '*/5 * * * *'

permissions:
  contents: write
  pages: write
  id-token: write

env:
  GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  actualiza-stock:
    runs-on: ubuntu-latest
    name: Check Stock Changes
    outputs:
      files_changed: ${{ steps.check.outputs.files_changed }}
    steps:
      - name: Checkout del código
        id: check
        uses: alvarogarciapiz/actions/GRIP/actualiza-stock@main

  push-repo:
    name: Update Stock (push-repo)
    if: needs.actualiza-stock.outputs.files_changed == 'true'
    runs-on: ubuntu-latest
    needs: actualiza-stock
    steps:
      - name: Push al repo para actualizar fichero de stock
        uses: alvarogarciapiz/actions/GRIP/push-repo@main

  deploy:
    name: Deploy
    if: needs.actualiza-stock.outputs.files_changed == 'true'
    needs: [actualiza-stock, push-repo]
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        uses: alvarogarciapiz/actions/GRIP/deploy@main
