name: Actualiza Stock
on:
  workflow_dispatch:
  schedule:
    - cron: '*/10 * * * *'

jobs:
  actualiza-stock:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v3

      - name: Copiar fichero data.json
        run: |
          cp data.json olddata.json

      - name: Run Python Stock Updates
        run: |
          pip install --upgrade pip
          pip install pandas
          python stock.py

      - name: Comprobar data
        id: check-data
        run: |
          if diff "data.json" "olddata.json" >/dev/null; then
            echo "files_changed=false" >> $GITHUB_OUTPUT
          else
            echo "files_changed=true" >> $GITHUB_OUTPUT
          fi

      - name: Push al repo
        if: env.files_changed == 'true'
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add data.json
          git commit -m "Modificación automática del fichero de stock"
          git push
