name: Actualiza Stock
on:
  workflow_dispatch:
  schedule:
    - cron: '*/10 * * * *'

jobs:
  actualiza-stock:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v3

      - name: Copiar fichero data.json
        run: |
          cp data.json olddata.json

      - name: Run Python Stock Updates
        run: |
          pip install --upgrade pip
          pip install pandas
          python stock.py

      - name: Comprobar data
        id: check-data
        run: |
          if diff "data.json" "olddata.json" >/dev/null; then
            echo "files_changed=false" >> $GITHUB_OUTPUT
            echo "El stock permanece igual"
          else
            echo "files_changed=true" >> $GITHUB_OUTPUT
            echo "El stock ha cambiado"
          fi
          echo "${{ files_changed }}"

  push-repo:
    if: ${{ needs.actualiza-stock-outputs.files_changed }} == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Push al repo
        run: |
          echo "${{ steps.check-data.outputs.files_changed }}"
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add *
          git commit -m "Modificación automática del fichero de stock"
          git push
