name: Actualiza Stock
on:
  workflow_dispatch:
  schedule:
    - cron: '*/10 * * * *'

jobs:
  actualiza-stock:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v3

      - name: Run Python Stock Updates
        run: |
          pip install --upgrade pip
          pip install pandas
          pip install json
          python stock.py
        
      - name: Push al repo
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add data.json
          git commit -m "Modificación automática del fichero de stock"
          git push
