name: Actualiza Stock
on:
  workflow_dispatch:
  schedule:
    - cron: '*/10 * * * *'

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  actualiza-stock:
    runs-on: ubuntu-latest
    name: Check Stock Changes
    steps:
      - name: Checkout del código
        uses: alvarogarciapiz/actions/GRIP/actualiza-stock@main

  stock-change:
    runs-on: ubuntu-latest
    name: Check func
    needs: actualiza-stock
    steps:
      - name: Checkout del código
        shell: bash
        run: echo ${{ needs.actualiza-stock.outputs.files_changed }}

  push-repo:
    if: needs.actualiza-stock.outputs.files_changed == 'true'
    runs-on: ubuntu-latest
    needs: actualiza-stock
    steps:
      - name: Push al repo para actualizar fichero de stock
        uses: alvarogarciapiz/actions/GRIP/push-repo@main

  deploy:
    if: needs.actualiza-stock.outputs.files_changed == 'true'
    needs: [actualiza-stock, push-repo]
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        uses: alvarogarciapiz/actions/GRIP/deploy@main
