name: Actualiza Stock
on:
  workflow_dispatch:
  schedule:
    - cron: '*/10 * * * *'

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  saluda:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - id: foo
        uses: alvarogarciapiz/actions/GRIP/example@main
        with:
          who-to-greet: 'Mona the Octocat'
      - run: echo random-number ${{ steps.foo.outputs.random-number }}
        shell: bash

  actualiza-stock:
    runs-on: ubuntu-latest
    name: Lee nuevo stock y comprueba cambios
    steps:
      - name: Checkout del código
        uses: alvarogarciapiz/actions/GRIP/actualiza-stock@main

  push-repo:
    if: needs.actualiza-stock.outputs.files_changed == 'true'
    runs-on: ubuntu-latest
    needs: actualiza-stock
    steps:
      - name: Push al repo para actualizar fichero de stock
        uses: alvarogarciapiz/actions/GRIP/push-repo@main

  deploy:
    if: needs.actualiza-stock.outputs.files_changed == 'true'
    needs: [actualiza-stock, push-repo]
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: '.'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
